import { Inter } from "next/font/google";
import "./globals.css";
import AnimationProvider from "@/components/animationProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Wilson's Portfolio App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AnimationProvider>{children}</AnimationProvider>
      </body>
    </html>
  );
}
